name: example
description: A sample command-line application.
version: 1.0.0

publish_to: "none"

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  html: ^0.15.1
  dart_pb_extensions_common:
    path: "../../"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
