name: dart_pb_extensions_common
description: Common models and type definitions for developing a Paperback source
version: 1.0.0
homepage: https://github.com/getBoolean/dart_pb_extensions_common

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  js: ^0.6.5
  html: ^0.15.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.16.0
