name: dart_pb_extensions_common
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  js: ^0.6.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
